# Generated by Django 3.1.1 on 2020-10-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delivery_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(default='nabil', max_length=15, null=1),
        ),
    ]
