# Generated by Django 3.1.1 on 2020-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201030_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='quantity',
            field=models.IntegerField(max_length=15, null=1),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(blank=1, max_length=15, null=1),
        ),
    ]
