# Generated by Django 3.1.1 on 2020-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201229_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.IntegerField(null=1),
        ),
    ]
