# Generated by Django 3.1.1 on 2021-05-08 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210509_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, null=1)),
                ('description', models.TextField(max_length=200, null=1)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 9, 1, 25, 50, 785688), null=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
